---
- include: base.yml
- name: Clone bench
  hosts: all
  user: "strella"
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
  tasks:
      - git:
          repo=https://github.com/frappe/bench
          dest=/home/strella/bench-repo
  tags:
    - bench_install

- name: Install bench
  hosts: all
  become: yes
  become_user: root
  tasks:

      - easy_install: name=pip executable=easy_install-2.7
      - pip:          name=/home/strella/bench-repo extra_args='-e'
  tags:
    - bench_install


- name: Setup bench
  hosts: all
  become: yes
  become_user: "strella"
  become_method: sudo
  gather_facts: false
  tasks:
    - bench:
        path: /home/strella/frappe-bench
        frappe_branch: "master"
        apps:
          - name: erpnext
            url: https://github.com/frappe/erpnext
            branch: "master"
          - name: erpnext_demo
            url: https://github.com/frappe/erpnext_demo
            branch: "master"
        mariadb_root_password: "frappe"
        sites:
          - name: erpnext.vm
            admin_password: "admin"
            apps:
              - erpnext
  tags:
    - bench_setup

- name: Setup Production
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
   - branch: "production"
  tasks:
    - shell: "bench setup sudoers strella"
      args:
        chdir: "/home/strella/frappe-bench"
        creates: "/home/strella/frappe-bench/config/supervisor.conf"
      when: branch == "master"
    - shell: "bench setup production strella"
      args:
        chdir: "/home/strella/frappe-bench"
        creates: "/home/strella/frappe-bench/config/supervisor.conf"
      when: branch == "master"
    - file: path="/home/strella/frappe-bench/logs/" recurse=yes owner="strella"
      when: branch == "master"
